# Generated by Django 5.1.6 on 2025-02-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdata_manager_userdata_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='employe',
        ),
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('MGR', 'Manager'), ('EMP', 'Employee')], default='EMP', max_length=3),
        ),
    ]
