# Generated by Django 5.1.6 on 2025-02-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userdata_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
    ]
