# Generated by Django 5.1.6 on 2025-02-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userdata_manager_remove_userdata_employe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], default='A', max_length=1),
        ),
    ]
